edenmind/OpenArabic

iac/azure-file-pvc.yaml, iac/azure-file-sc.yaml, iac/database.yaml
=> Set up persistent volume claims for database

frontend/src/app/app.module.ts, frontend/src/app/text/text.component.ts
=> Title exposed in HTML title

api/MicroServiceFacades/TashkeelFacade.cs, api/Services/TextService.cs
=> CPU at 100% when Taskeel fails

.github/workflows/linter.yml
=> Add superlinter

.github/workflows/pr-compliance.yml
=> feat(github): :sparkles: add pr comliance check

mobile/.prettierrc.js, mobile/.yarnrc.yml, mobile/babel.config.js, mobile/mocks.js
=> Implement correct LINT in all .js-files

mobile/__tests__/Reducers.test.js
=> Write tests for reducers

mobile/.expo/packager-info.json, mobile/__tests__/Colors.test.js, mobile/constants/colors.js, mobile/screens/About/AboutNavigator.js, mobile/screens/Categories/CategoryDrawer.js, mobile/screens/Texts/TextList/TextCard.js, mobile/screens/Texts/TextNavigator.js
=> Move colors to class

.github/workflows/pr-compliance.yml
This PR addresses some of the notes from #732 .
💔Thank you!
=> ci: Update pr-compliance.yml

mobile/__tests__/AboutNavigator.test.js, mobile/__tests__/Heading.test.js, mobile/__tests__/Sentence.test.js, mobile/__tests__/Spinner.test.js, mobile/__tests__/TextCard.test.js, mobile/screens/Texts/TextList/TextCard.js
=> Add basic tests for components

mobile/__tests__/About.test.js, mobile/__tests__/ApiService.test.js, mobile/__tests__/Colors.test.js, mobile/__tests__/Reducers.test.js, mobile/__tests__/Settings.test.js, mobile/__tests__/SnackButton.test.js, mobile/components/SnackButton.js, mobile/components/Spinner.js, workspace.code-workspace
=> feat(mobile): :sparkles: add snackbutton

mobile/.expo/packager-info.json, mobile/__tests__/TextList.test.js, mobile/screens/Categories/CategoryDrawer.js, mobile/screens/Texts/TextList/TextList.js, mobile/screens/Texts/TextNavigator.js
=> Flatlist for tables

mobile/jest.config.js, mobile/package.json, workspace.code-workspace
=> Add jest test runner

mobile/.expo/packager-info.json, mobile/__tests__/TextItem.test.js, mobile/__tests__/TextRelated.test.js, mobile/components/TextItem.js, mobile/redux/actions.js, mobile/redux/reducers.js, mobile/screens/Texts/Text/TextArabic.js, mobile/screens/Texts/Text/TextEnglish.js, mobile/screens/Texts/Text/TextRelated.js, mobile/screens/Texts/Text/TextScreen.js, mobile/screens/Texts/TextList/TextList.js
=> Related texts

mobile/__tests__/Heading.test.js, mobile/__tests__/ModalScrollView.test.js, mobile/components/ModalScrollView.js, mobile/components/WordPairs.js, mobile/screens/Texts/Text/Sentences.js, mobile/screens/Texts/Text/TextArabic.js, mobile/screens/Texts/Text/TextRelated.js
=> Words in sentence modal are not shown

.github/workflows/main.yml
=> Configure branch trigger for build

package/templates/api-deployment.yaml, package/templates/mongo-deployment.yaml, package/templates/tashkeel-deployment.yaml, package/templates/web-deployment.yaml
=> Set requirements for cpu and memory

package/templates/api-deployment.yaml, package/templates/web-deployment.yaml
=> Increase replica sets

package/templates/mongo-deployment.yaml
=> Fix typo in mongo-deployment

.github/workflows/build-publish.yaml, mobile/.expo/packager-info.json, mobile/app.test.js, mobile/constants/urls.publish.js
=> Set correct variables at build time web/mobile

mobile/.expo/packager-info.json, mobile/components/selectable-chip.js, mobile/constants/urls.js, mobile/screens/text-quiz-vocabularies.js
=> Right adjust arabic text in quiz

mobile/constants/urls.js
=> Fix link for share button

web/src/screens/text-add-words.js
=> Image is not shown in main text

mobile/screens/__snapshots__/about.test.js.snap, mobile/screens/about.js
=> Add spacing on info screen

mobile/constants/urls.development.js, mobile/constants/urls.development.test.js, mobile/constants/urls.publish.test.js, start-dev-environment.sh
=> Use env vars in Mobile

start-dev-environment.sh
=> Persist Mongo data when developing

mobile/components/modal-scroll-view.js, mobile/components/pressable-opacity.js, mobile/components/selectable-chip.js, mobile/components/snack-button.js, mobile/redux/store.js, mobile/routes/root.js, mobile/routes/text-drawer.js, mobile/routes/text-tabs.js, mobile/routes/text.js, mobile/screens/about.js, mobile/screens/category.js, mobile/screens/text-bilingual-heading.js, mobile/screens/text-bilingual-sentences-word-pairs.js, mobile/screens/text-bilingual-sentences.js, mobile/screens/text-quiz-vocabularies.js, mobile/screens/text-quiz.js, mobile/services/api-service.js, mobile/services/api-service.test.js
=> Minor cleanup in mobile

mobile/routes/text-drawer.js
=> Don't use category name for id in drawer, use id

web/src/screens/text-add-words.js
=> Warn if vocabulary text is so large that it will not fit selectable chip

web/src/components/nav.js, web/src/screens/about.js, web/src/screens/authors-add.js, web/src/screens/authors-update.js, web/src/screens/authors.js, web/src/screens/categories-add.js, web/src/screens/categories-update.js, web/src/screens/categories.js, web/src/screens/privacy.js, web/src/screens/text-add-heading.js, web/src/screens/text-add-publish.js, web/src/screens/text-add-words-generate.js, web/src/screens/text-add.js, web/src/screens/text-list-card.js, web/src/screens/text-list-id.js, web/src/screens/text-list.js, web/src/screens/texts.js, web/src/services/api-service.js
=> Implement new api service

web/src/components/nav-app-bar.js
=> Remove red line below link

web/src/components/nav-drawer.js, web/src/screens/text-add-words.js, web/src/screens/texts.js, web/src/services/api-service.js
=> The word tab crashes if entering it directly

api/tests/routes/categories.test.js, api/tests/routes/texts.test.js
=> Make test that cheks that API rejects faulty posts

api/controllers/categories.js, api/controllers/texts.js, api/routes/authors.js, api/routes/categories.js, api/routes/images.js, api/routes/texts.js, api/schemas/authors.js, api/schemas/categories.js, api/schemas/images.js, api/schemas/texts.js
=> Split listTexts in two functions

web/src/screens/authors-list.js, web/src/screens/authors.js, web/src/screens/authors.test.js, web/src/screens/text-add-words-generate.js, web/src/services/api-service.test.js, web/src/services/dictionary.test.js
=> Fetch from Google and check if word is in sentence

.github/workflows/build-publish.yaml, .github/workflows/build-push-deploy.yml, .github/workflows/build-test.yml, .github/workflows/pr-compliance.yml
=> Make sure that dependency checks run

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .vscode/settings.json, README.md, docs/PULL_REQUEST_TEMPLATE.md
=> docs(docs): :memo: refine documentation and processes

api/Dockerfile, docker-compose-default.env, docker-compose.yml, services/tashkeel/Dockerfile, static/Dockerfile
the dockerfiles will use a LTS version and allow updates of minor and patch but not major
Fixes #1283
=> ci(multiple): :construction_worker: build all dockerfiles with an LTS version

README.md, database/init-database-and-user.js, start-dev-environment.sh
=> docs: :memo: add explanation on how to start dev environment + small doc fixes

.github/workflows/build-push-deploy.yml, .github/workflows/build-test.yml, mobile/jest.config.js
=> Add code codecoverage at buildtime

.github/workflows/code-ql.yml, README.md
=> build: :sparkles: add code ql scan to pull requests

.github/workflows/build-push-deploy.yml, package/.gitignore
=> fix(helm): :bug: change path to the packaged helm chart

.github/workflows/pr-compliance.yml
=> ci: :green_heart: run pr checks even for team members

.github/workflows/code-ql.yml
=> build: :construction_worker: test only run on prs

.github/workflows/analyze-with-codeql.yml, .github/workflows/build-and-publish-to-expo.yml, .github/workflows/build-push-and-deploy-containers.yml, .github/workflows/dependency-review.yml, .github/workflows/pr-compliance.yml, .github/workflows/test-and-lint.yml, README.md
=> docs: :memo: refine documentation and clean action naming

.github/dependabot.yml, .github/workflows/code-ql.yml
=> build: :construction_worker: add docker scan to dependabot

.github/workflows/test-and-lint.yml, package/templates/api-canary.yaml
=> fix: :bug: only use finder once

README.md
=> docs(repo): :memo: add information about calver based on hijri calendar

api/README.md, database/README.md, mobile/README.md, package/README.md, services/README.md, static/README.md, web/README.md
=> docs(repo): :memo: add a basic README to every subdirectory

web/src/screens/text-list-heading-home.js
=> feat(web): :sparkles: add hijri date to homepage (#1361)

package/Chart.yaml
=> docs(repo): :memo: add metadata to describe the chart #1410
